version: '3'
services:
  ingress:
    build:
      context: ./nginx
      args:
        port: 8020
        port_app: 1234
    tty: true
    links:
      - application
    ports:
      - "8080:8020"
  application:
    build:
      context: ./backend
      args:
        port: 1234
    tty: true