version: '3'
services:
  ingress:
    build:
      context: ./nginx
      args:
        port: ${PORT_NGINX}
        port_app: ${PORT_APP}
    tty: true
    links:
      - application
    ports:
      - "${PORT_INGRESS}:${PORT_NGINX}"
  application:
    build:
      context: ./backend
      args:
        port: ${PORT_APP}
    tty: true