version: '3'
services:
  ingress:
    build:
      context: ./nginx
      args:
        port: ${PORT_NGINX}
        port_app: ${PORT_APP}
    tty: true
    links:
      - application
    ports:
      - "${PORT_INGRESS}:${PORT_NGINX}"
    volumes:
      - dist:/var/www/app/
    depends_on:
      - frontend-build
  application:
    build:
      context: ./backend
      args:
        port: ${PORT_APP}
    tty: true
  frontend-build:
    build: frontend
    volumes:
      - dist:/var/www/app/
volumes:
  dist: {}